set(CMAKE_SYSTEM_NAME Linux)

set(CMAKE_C_COMPILER $ENV{RPI_ROOT}/arm-linux-gnueabihf-gcc)
set(CMAKE_CXX_COMPILER $ENV{RPI_ROOT}/arm-linux-gnueabihf-g++)
set(CMAKE_CXX_LINKER $ENV{RPI_ROOT}/arm-linux-gnueabihf-ld)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
